# Node 10.x
FROM node:10-alpine

# Add bin deps to image.
RUN apk update && apk add bash

# Create app directory.
WORKDIR /var/www/my-redis

RUN npm rebuild

# Run and restart on changes.
CMD node ./dist/index.js
