# Node 10.x
FROM node:10-alpine

# Add bin deps to image.
RUN apk update && apk add bash

# Create app directory.
WORKDIR /var/www/ec-api

COPY package*.json ./

# Install NPM production deps and cleanup.
RUN npm i

COPY . .

# Clean and Build
RUN npm run clean
RUN npm run build

# Run and restart on changes.
CMD node ./dist/index.js
